name: SimpleFactions
version: '1.0-SNAPSHOT'
main: daveiiii.simpleFactions.SimpleFactions
api-version: '1.21'
depend:
  - Essentials
commands:
  f:
    usage: /f <subcommand>
  discord:
    usage: /discord
